# Generated by Django 4.2.4 on 2023-08-22 16:38

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.RemoveField(
            model_name='employer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='boss',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='department',
            name='boss',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boss', to='app.employer', verbose_name='Руководитель отдела'),
        ),
        migrations.AddField(
            model_name='department',
            name='depend_on',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='app.department', verbose_name='Старший отдел'),
        ),
        migrations.AddField(
            model_name='department',
            name='employer',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employers', to='app.employer', verbose_name='Штатный сотрудник'),
        ),
        migrations.AddField(
            model_name='department',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='vacancy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='name',
            field=models.CharField(default=0, max_length=200, verbose_name='ФИО сотрудника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='salary',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employer',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.position', verbose_name='Должность'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('depend_on', 'slug')},
        ),
    ]
