# Generated by Django 4.2.4 on 2023-08-23 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_department_boss_department_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='boss',
        ),
        migrations.RemoveField(
            model_name='department',
            name='employer',
        ),
        migrations.AddField(
            model_name='employer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.department', verbose_name='Отдел'),
        ),
    ]
