# Generated by Django 4.2.4 on 2023-08-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_department_boss_remove_department_employer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='depend_on',
            new_name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('parent', 'slug')},
        ),
    ]
