# Generated by Django 4.2.4 on 2023-08-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_department_staffing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='department',
            name='staffing',
            field=models.IntegerField(default=2000, verbose_name='Штатная численность'),
        ),
        migrations.RemoveField(
            model_name='department',
            name='slug',
        ),
    ]
