# Generated by Django 4.2.4 on 2023-08-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_department_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='position',
            name='slug',
        ),
    ]
