# Generated by Django 4.2.4 on 2023-08-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_employer_slug_remove_position_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
        migrations.AddField(
            model_name='department',
            name='fullname',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Название отдела'),
        ),
    ]
