# Generated by Django 4.2.4 on 2023-08-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_department_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='birth_date',
            field=models.DateField(auto_now=True),
        ),
    ]
