# Generated by Django 4.2.4 on 2023-08-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_employer_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
