# Generated by Django 4.2.4 on 2023-08-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_employer_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
        migrations.AddField(
            model_name='employer',
            name='photo_small',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='salary',
            field=models.IntegerField(verbose_name='Жалование'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='work_since',
            field=models.DateField(verbose_name='Дата трудоустройства'),
        ),
    ]
