# Generated by Django 4.2.4 on 2023-08-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_employer_photo_employer_photo_small_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='photo_small',
        ),
        migrations.AlterField(
            model_name='employer',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo/', verbose_name='Фото'),
        ),
    ]
